'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import {ArrowUp,ArrowUpRight,Check,ChevronDown,ChevronRight,FileText,Folder,MessageSquare,PanelLeftClose,PanelRight,Plus,Search,ShieldCheck,Sparkles,Square,X,Download,Paperclip,Command,BookOpen,LayoutGrid} from 'lucide-react';
import {B} from '@/components/errandly/config';

type Message={role:'user'|'assistant';text:string};
type Chat={id:string;title:string;messages:Message[];files:string[];instructions:string};
const seed:Chat[]=[{id:'welcome',title:'October expense report',messages:[{role:'user',text:'Help me make sense of my October expenses. Put together a simple summary and highlight where I can save.'},{role:'assistant',text:'Here’s a little clarity for your month. I grouped the sample expenses into four categories and put the key takeaways in one place.'}],files:['October invoices.csv','Workspace notes.md'],instructions:'Keep things concise. Use USD for expenses. Ask before making changes to files.'},{id:'research',title:'A head start on my research',messages:[{role:'user',text:'Help me structure my research notes.'},{role:'assistant',text:'Start with a central question, then group your notes into themes. For each theme, keep the source, key finding, and any open questions together. This is a sample response for the interface preview.'}],files:['Research outline.md'],instructions:''},{id:'files',title:'A calmer Downloads folder',messages:[{role:'user',text:'Suggest a structure for my Downloads folder.'},{role:'assistant',text:'Try four folders: Documents, Images, Spreadsheets, and Archives. Review the proposed structure before moving anything. This preview does not access or change files on your computer.'}],files:[],instructions:''}];
const suggestions=[{icon:Folder,title:'Bring a little order',text:'Organize a folder of scattered files',prompt:'Help me organize my Downloads folder.'},{icon:BookOpen,title:'Find the useful parts',text:'Turn long documents into clear notes',prompt:'Help me summarize my research documents.'},{icon:LayoutGrid,title:'Make the numbers click',text:'Build a report from your spreadsheets',prompt:'Help me create an expense report.'}];
const steps=['Getting the context together','Connecting the useful details','Putting the finishing touches'];
export default function Workspace(){
 const[chats,setChats]=useState<Chat[]>(seed);const[active,setActive]=useState('welcome');const[input,setInput]=useState('');const[search,setSearch]=useState('');const[context,setContext]=useState(true);const[sidebar,setSidebar]=useState(false);const[busy,setBusy]=useState(false);const[stage,setStage]=useState(0);const[ready,setReady]=useState(false);const[notice,setNotice]=useState('');
 const fileRef=useRef<HTMLInputElement>(null);const endRef=useRef<HTMLDivElement>(null);const timer=useRef<ReturnType<typeof setInterval>|null>(null);
 const chat=chats.find(c=>c.id===active)||chats[0];
 useEffect(()=>{if(window.innerWidth<=1000)setContext(false);try{const saved=JSON.parse(localStorage.getItem('errandly-workspace-v1')||'null');if(Array.isArray(saved)&&saved.length&&saved.every(c=>typeof c.id==='string'&&typeof c.title==='string'&&typeof c.instructions==='string'&&Array.isArray(c.files)&&c.files.every((f:unknown)=>typeof f==='string')&&Array.isArray(c.messages)&&c.messages.every((m:Message)=>(m.role==='user'||m.role==='assistant')&&typeof m.text==='string'))){setChats(saved);setActive(saved[0].id)}}catch{}setReady(true);return()=>{if(timer.current)clearInterval(timer.current)}},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('errandly-workspace-v1',JSON.stringify(chats))}catch{setNotice('Browser storage is unavailable. Chats will last for this session.')}},[chats,ready]);
 useEffect(()=>{endRef.current?.scrollIntoView({behavior:'smooth',block:'end'})},[chat?.messages.length,busy]);
 function update(patch:Partial<Chat>){setChats(all=>all.map(c=>c.id===active?{...c,...patch}:c))}
 function stop(){if(timer.current)clearInterval(timer.current);timer.current=null;setBusy(false)}
 function select(id:string){stop();setActive(id);setInput('');setSidebar(false)}
 function newChat(){stop();const id=crypto.randomUUID();setChats(all=>[{id,title:'A fresh start',messages:[],files:[],instructions:''},...all]);setActive(id);setInput('');setSidebar(false)}
 function send(value=input){if(!value.trim()||busy)return;const text=value.trim();const id=active;setChats(all=>all.map(c=>c.id===id?{...c,title:c.messages.length?c.title:text.slice(0,38),messages:[...c.messages,{role:'user',text}]}:c));setInput('');setBusy(true);setStage(0);let tick=0;timer.current=setInterval(()=>{tick++;if(tick<3){setStage(tick);return}stop();setChats(all=>all.map(c=>c.id===id?{...c,messages:[...c.messages,{role:'assistant',text:`I’ve added your request to this conversation: “${text}”\n\nIn the full app, I would use this chat’s attached files and instructions to plan the work with you. This interactive design preview uses simulated responses; no AI model is connected and attached file contents are not read.`}]}:c))},1600)}
 function download(){const content=chat.messages.map(m=>`${m.role==='user'?'You':'Errandly'}\n${m.text}`).join('\n\n');const url=URL.createObjectURL(new Blob([content],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download=`${chat.title}.txt`;a.click();URL.revokeObjectURL(url)}
 return <main id="main" className={`ew ${context?'with-context':''}`}>
 <aside className={`ew-sidebar ${sidebar?'is-open':''}`}>
 <Link href={B} className="ew-brand"><img className="ew-official-logo" src={B+"/errandly-logo.png"} width="2513" height="518" alt="Errandly"/><span className="ew-beta">PREVIEW</span></Link>
 <button className="ew-new" onClick={newChat}><Plus size={17}/>New conversation<kbd>＋</kbd></button>
 <label className="ew-search"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search conversations" aria-label="Search conversations"/></label>
 <div className="ew-space-label">WORKSPACE</div><button className="ew-personal" onClick={()=>{setSearch('');setSidebar(false)}}><span className="ew-folder"><Folder size={16}/></span>Personal workspace<ChevronDown size={14}/></button>
 <div className="ew-history-title">Conversations<span>{chats.length}</span></div>
 <nav className="ew-history" aria-label="Chat history">{chats.filter(c=>c.title.toLowerCase().includes(search.toLowerCase())).map(c=><button key={c.id} className={active===c.id?'active':''} onClick={()=>select(c.id)}><MessageSquare size={15}/><span>{c.title}</span>{active===c.id&&<span className="ew-selected-dot"/>}</button>)}{!chats.some(c=>c.title.toLowerCase().includes(search.toLowerCase()))&&<p className="ew-empty-search">No conversations found.</p>}</nav>
 <div className="ew-sidebar-bottom"><div className="ew-private"><ShieldCheck size={19}/><div>A space that’s yours<small>Chat history saved in this browser</small></div></div><div className="ew-profile"><span className="ew-avatar">Y</span><div>Your workspace<small>Personal · Design preview</small></div><Link href={B} aria-label="Back to Errandly website"><ArrowUpRight size={17}/></Link></div></div>
 </aside>
 {sidebar&&<button className="ew-scrim" aria-label="Close navigation" onClick={()=>setSidebar(false)}/>}
 <section className="ew-main"><div className="ew-topbar"><button className="ew-mobile-menu ew-icon" aria-label="Open navigation" onClick={()=>setSidebar(true)}><PanelLeftClose size={18}/></button><span className="ew-breadcrumb">Personal<ChevronRight size={13}/></span><span className="ew-chat-title">{chat.title}</span><div className="ew-top-actions"><span className="ew-preview-dot"/> <span className="ew-preview-label">Interactive preview</span><button className="ew-icon" onClick={download} title="Export conversation" aria-label="Export conversation"><Download size={17}/></button><button className={`ew-icon ${context?'selected':''}`} onClick={()=>setContext(!context)} aria-label="Toggle conversation context" aria-expanded={context}><PanelRight size={18}/></button></div></div>
 <div className="ew-scroll"><div className="ew-conversation">
 {chat.messages.length===0?<div className="ew-welcome"><img className="ew-official-mark" src={B+"/errandly-mark.svg"} width="80" height="62" alt=""/><p>A LITTLE SPACE TO THINK</p><h1>What’s on your mind?</h1><div>From a loose thought to a finished task.<br/>Let’s make room for your best work.</div><div className="ew-suggestions">{suggestions.map(s=><button key={s.title} onClick={()=>send(s.prompt)}><s.icon size={21}/><strong>{s.title}</strong><span>{s.text}</span><ArrowUpRight size={15}/></button>)}</div></div>:<><div className="ew-day"><span/>TODAY<span/></div>{chat.messages.map((m,i)=><article key={i} className={`ew-message ew-${m.role}`}><div className="ew-message-label">{m.role==='user'?<span className="ew-small-avatar">Y</span>:<img className="ew-official-mark small" src={B+"/errandly-mark.svg"} width="24" height="19" alt=""/>}<strong>{m.role==='user'?'You':'Errandly'}</strong><small>{m.role==='user'?'':'Your thinking partner'}</small></div><div className="ew-message-text">{m.text}</div>{chat.id==='welcome'&&i===1&&<><div className="ew-report"><div className="ew-report-heading"><div><span className="ew-report-icon"><LayoutGrid size={19}/></span><strong>October, at a glance<small>Expense summary · Sample data</small></strong></div><span className="ew-ready"><Check size={11}/>Ready</span></div><div className="ew-total"><span>Total expenses<strong>$1,463<span>.00</span></strong></span><div className="ew-mini-chart">{[35,56,42,80,59,91,65,46,77,61,98,73].map((n,i)=><i key={i} style={{height:n+'%'}}/>)}</div></div><div className="ew-category-bar"><i/><i/><i/><i/></div><div className="ew-categories">{[['Workspace','$650','44%'],['Equipment','$379','26%'],['Software','$248','17%'],['Travel','$186','13%']].map(([name,amount,percent],j)=><div key={name}><i data-category={j}/><span>{name}</span><strong>{amount}</strong><small>{percent}</small></div>)}</div><div className="ew-report-foot"><ShieldCheck size={13}/>Illustrative report · 12 sample invoices</div></div><p className="ew-takeaway"><span>↳</span> A small opportunity: review recurring software subscriptions before next month.</p><button className="ew-followup" onClick={()=>send('Help me review recurring software subscriptions.')} disabled={busy}>Find a little room to save<ArrowUpRight size={14}/></button></>}</article>)}</>}
 {busy&&<div className="ew-thinking" role="status" aria-live="polite"><div className="ew-orbit"><i/><i/><i/><img className="ew-official-mark small" src={B+"/errandly-mark.svg"} width="24" height="19" alt=""/></div><div><strong>{steps[stage]}<span className="ew-dots"><i/><i/><i/></span></strong><p>A little thought. A little less on your plate.</p><div className="ew-progress">{steps.map((s,i)=><span className={i<=stage?'on':''} key={s}/>)}</div></div><span className="ew-simulation">DEMO</span></div>}
 <div ref={endRef}/></div></div>
 <div className="ew-compose-wrap">{notice&&<div className="ew-notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss notification"><X size={13}/></button></div>}<form className={`ew-compose ${busy?'is-thinking':''}`} onSubmit={e=>{e.preventDefault();send()}}><textarea aria-label="Message Errandly" placeholder="A question, a task, a little less on your plate…" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send()}}}/><div className="ew-compose-tools"><button type="button" className="ew-icon" onClick={()=>fileRef.current?.click()} aria-label="Attach files"><Plus size={20}/></button><span className="ew-compose-model"><Sparkles size={14}/>Errandly<span className="ew-model-tag">Demo</span></span><span className="ew-context-count"><Paperclip size={12}/>{chat.files.length} in context</span>{busy?<button type="button" className="ew-send" onClick={stop} aria-label="Stop response"><Square size={15} fill="currentColor"/></button>:<button className="ew-send" disabled={!input.trim()} aria-label="Send message"><ArrowUp size={19}/></button>}</div></form><p className="ew-disclaimer">A design preview with simulated responses.<span> Made for a calmer kind of work.</span></p></div>
 </section>
 {context&&<aside className="ew-context"><div className="ew-context-heading"><span>Conversation context</span><button className="ew-icon" onClick={()=>setContext(false)} aria-label="Close context"><X size={16}/></button></div><div className="ew-context-body"><div className="ew-context-intro"><span className="ew-context-emblem"><Command size={21}/></span><h2>The whole picture.</h2><p>Everything this conversation<br/>can draw from, in one place.</p></div><div className="ew-context-section"><h3>Attached files<span>{chat.files.length}</span><button className="ew-icon" onClick={()=>fileRef.current?.click()} aria-label="Add context files"><Plus size={15}/></button></h3>{chat.files.map((file,i)=><div className="ew-file" key={`${file}-${i}`}><span><FileText size={18}/></span><div title={file}>{file}<small>{chat.id==='welcome'||chat.id==='research'?'Sample reference':'Filename only · Preview'}</small></div><button aria-label={`Remove ${file}`} onClick={()=>update({files:chat.files.filter((_,j)=>i!==j)})}><X size={12}/></button></div>)}<button className="ew-add-files" onClick={()=>fileRef.current?.click()}><Paperclip size={14}/>Add files to this chat</button></div><div className="ew-context-section"><h3>Instructions<span className="ew-auto-save">Auto-saved</span></h3><textarea aria-label="Conversation instructions" value={chat.instructions} placeholder="How would you like Errandly to help?" onChange={e=>update({instructions:e.target.value})}/><p className="ew-field-help">A little guidance goes a long way.</p></div><div className="ew-context-section"><h3>Conversation memory</h3><div className="ew-memory"><span className="ew-memory-dot"/><div>Keeping the thread<small>{chat.messages.length} messages in this conversation</small></div></div><p className="ew-memory-note">Your messages and instructions stay together when you return to this chat.</p></div><button className="ew-export" onClick={download}><Download size={14}/>Export conversation<ArrowUpRight size={13}/></button></div><div className="ew-context-footer"><ShieldCheck size={14}/><span>Stored in this browser.<br/>You’re always in control.</span></div></aside>}
 <input ref={fileRef} type="file" multiple hidden onChange={e=>{const names=Array.from(e.target.files||[]).map(f=>f.name);update({files:[...new Set([...chat.files,...names])]});setNotice('Added file names to context. File contents are not read in this preview.');e.target.value=''}}/>
 </main>
}
