import {InterfacePreview} from '@/components/errandly/launch-features';
import {MacHelpVideo} from '@/components/errandly/mac-help-video';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {ArrowDown,ArrowUpRight,ShieldCheck} from 'lucide-react';
import {CTA,FAQ,Logo,ProductDemo} from '@/components/errandly/site';
import {B,downloadHref} from '@/components/errandly/config';
type PageData={label:string;title:string;intro:string;sections:[string,string][]};
const pages:Record<string,PageData>={
'product':{label:'Meet Errandly',title:'An extra pair of hands. On your Mac.',intro:'From a folder full of files to a finished piece of work. Errandly is being built to take everyday tasks off your plate.',sections:[['Start with what you need','Describe the outcome in plain language. Errandly will break it into steps and work only with the files and folders you select.'],['See the plan. Stay in control.','Review sensitive changes before they happen. The planned agent keeps a task history, verifies results, and offers undo for supported file operations.'],['Finish with something useful','A spreadsheet, a set of study notes, an organized folder. Outputs are saved in a location you choose on your Mac.']]},
'features/files':{label:'File organization',title:'A place for everything.',intro:'Turn a crowded Downloads folder into a workspace you can think in. Preview the changes, then let Errandly put things in order.',sections:[['Choose the folder','Give Errandly access to a specific folder. It will inspect supported files and suggest a structure based on file type and your instructions.'],['Review before moving','See proposed destinations before approving file moves. Your original files remain under your control.'],['Keep a clear history','The planned activity log shows what moved and where. Supported operations can be reversed without digging through folders.']]},
'features/documents':{label:'Document intelligence',title:'Read less. Understand more.',intro:'Make sense of the documents you already have. Turn selected PDFs into summaries, useful notes, and questions worth asking.',sections:[['Get to the useful parts','Ask for key ideas, compare supported documents, or create a topic-wise summary. Errandly is designed to process these files locally.'],['Build your next study session','Bring together lecture materials, prepare notes, and generate practice questions from the source documents you choose.'],['Keep the source in sight','Source references will be shown when available. Always review generated summaries against the original, especially when details matter.']]},
'features/reports':{label:'Spreadsheets & reports',title:'From scattered numbers to a clear picture.',intro:'Bring invoices and sales spreadsheets together. Ask for the report you need and keep the result right on your Mac.',sections:[['A simpler month-end','Extract information from supported invoices, categorize expenses, and generate a monthly summary from selected local files.'],['Calculations you can inspect','The planned calculation engine uses deterministic code for totals and numeric operations. Generated reports are designed to be editable and reviewable.'],['Outputs that fit your work','Save spreadsheets and reports to your chosen output folder. Review the result before you share it or use it for a decision.']]},
'features/local-ai':{label:'Local intelligence',title:'Your AI should feel at home.',intro:'Errandly’s core is designed to run on your Mac. Your processing power, your storage, your choice.',sections:[['Built for offline work','After installation and local model setup, supported core tasks are designed to work without an internet connection.'],['No mandatory AI subscription','The planned free core uses an on-device model. You won’t need paid API credits for supported local tasks.'],['Online only when you choose','Optional external AI is a later feature. It will require your own credentials and explicit control over what is sent to a provider.']]},
'use-cases/students':{label:'For students & researchers',title:'More learning. Less sorting.',intro:'A private study companion for your lecture PDFs, research materials, and the files that pile up between classes.',sections:[['Bring your materials together','Select a folder of lecture PDFs and ask Errandly to organize the material into topics.'],['Make revision easier','The planned document tools turn source material into study notes, summaries, and practice questions.'],['Keep your research close','Documents and generated notes are designed to stay in your local workspace. Review citations and check important details against the source.']]},
'use-cases/business':{label:'For business owners',title:'Get back to running your business.',intro:'Spend less time collecting invoices and wrestling with spreadsheets. Get a clear, editable report from the files you already have.',sections:[['Organize your month','Group supported business documents and invoices into a structure you approve.'],['Understand the numbers','Ask for a sales summary or expense breakdown. Planned numeric checks help make the calculations inspectable.'],['Keep business files local','The core workflow is designed to process and save your documents on your own computer.']]},
'use-cases/freelancers':{label:'For freelancers',title:'More of the work you love.',intro:'Make room for creative work by handing off the repetitive parts of project administration.',sections:[['Start from the brief','Analyze a client brief and generate an editable proposal outline in your local workspace.'],['Bring order to projects','Organize project files and prepare summaries without creating another cloud workspace.'],['Keep the final say','Review generated text and proposed file changes before they become part of your workflow.']]},
'about':{label:'About Errandly',title:'A little less on your plate.',intro:'We believe useful AI should help finish the everyday work—and let you keep ownership of it.',sections:[['Built by Foxmen Studio','Errandly is a macOS application in development at Foxmen Studio. Our first focus is practical, local automation for students, business owners, and independent professionals.'],['Useful before everything else','We’re starting with three everyday workflows: organizing files, understanding documents, and creating reports. Reliability comes before promises of doing everything.'],['Your computer is enough','Our planned architecture puts core AI, task history, models, and outputs on the user’s own device. No mandatory developer-hosted storage or backend is needed for ordinary use.']]},
'security':{label:'Security by design',title:'Helpful. With boundaries.',intro:'Errandly’s planned security model starts with a simple idea: useful access should be specific, visible, and under your control.',sections:[['Permission-based access','The application is designed to work with user-selected folders and supported tools. It will not request unrestricted computer control for its first release.'],['Approval before sensitive changes','File moves and other sensitive operations require review. Supported file changes will have an undo path, and partial failures must be reported clearly.'],['A release we can stand behind','Security testing, signed distribution, and Apple notarization are release requirements. These are development goals, not claims of a completed audit or certification.']]},
'data-use':{label:'Your data & control',title:'Your work belongs to you.',intro:'The planned core stores documents, conversations, models, and outputs on your computer by default.',sections:[['Local by default','Documents remain in their folders. Models and local application data live on your Mac. Generated reports go to an output folder you select.'],['Optional means optional','External AI integrations are planned for a later release. They will use your own provider account and require your authorization to transmit data.'],['Export, delete, and move on','The product requirements include exporting and deleting application data. Uninstalling the app must not remove unrelated files or generated business documents.']]},
'careers':{label:'Careers',title:'Build something quietly useful.',intro:'We’re building a thoughtful desktop assistant for the work people do every day.',sections:[['No open roles announced','Foxmen Studio has not published open positions for Errandly yet. Any future opportunities will appear on this page.'],['What we care about','Reliable local software, clear interfaces, user ownership, and a small set of workflows done well.']]},
'privacy':{label:'Privacy',title:'Privacy starts with the product.',intro:'Errandly is still in development. This page describes our planned data practices; the final application privacy policy will be published before release.',sections:[['The planned desktop experience','Core documents, task history, models, and generated outputs are designed to remain on your device. No developer-hosted document storage is required for ordinary use.'],['This website','This website does not include an email signup, advertising tracker, or customer account system. The hosting provider may process request information needed to serve the site.'],['Before launch','The final policy will identify the operator, support contact, any optional telemetry, retention practices, and applicable privacy rights. Those details are not finalized here.']]},
 'terms':{label:'Release information',title:'Before you download.',intro:'Errandly has not been released. No software purchase or download agreement is offered on this preview website.',sections:[['Pre-release product information','Descriptions and demonstrations illustrate the planned product. Features, compatibility, and availability may change as development and testing continue.'],['Licensing at launch','The application license and final terms of service will be published alongside the first public installer.'],['Product demonstrations','The on-site interfaces and film use fictional sample data to illustrate intended workflows. They are concept previews, not recordings of a released application.']]},
'blog/introducing-errandly':{label:'Journal / Introduction',title:'A little less on your plate.',intro:'Introducing Errandly: an everyday AI assistant that starts with the computer you already own.',sections:[['The work around the work','There is a particular kind of work that fills the spaces between everything else: sorting downloads, pulling numbers from invoices, turning lecture PDFs into usable notes. It matters, but it rarely feels like progress.'],['A useful place to start','Errandly is being built around three workflows: file organization, document intelligence, and local reports. Tell it the outcome, review the plan, and keep control of the result.'],['Still in the making','We’re in development. This website is a first look at the product direction. We’ll publish the installer, tested requirements, and release notes here when it’s ready.']]},
'blog/local-first':{label:'Journal / Product philosophy',title:'Why your AI should feel at home.',intro:'Useful intelligence should not require giving your entire workspace a new address.',sections:[['Start with ownership','Your Mac already has the storage and computing resources you use every day. Errandly’s core is designed to work there, with your files in your folders.'],['Offline is a product decision','Local inference allows supported tasks to continue without a network connection after model setup. Performance will depend on the model and available hardware.'],['Keep the choice open','Some tasks may benefit from external AI. Future optional integrations will make that a choice, using your own credentials and explicit authorization. The core remains local.']]}
};
const special=['download','pricing','docs','help','blog','changelog','roadmap','brand'];
export function generateStaticParams(){return [...Object.keys(pages),...special].map(s=>({slug:s.split('/')}))}
export async function generateMetadata({params}:{params:Promise<{slug:string[]}>}){const{slug}=await params;const key=slug.join('/');return{title:pages[key]?.title??key.charAt(0).toUpperCase()+key.slice(1)}}
export default async function Page({params}:{params:Promise<{slug:string[]}>}){const{slug}=await params;const key=slug.join('/');if(!pages[key]&&!special.includes(key))notFound();const page=pages[key];if(page)return <main id="main"><div className="wrap"><section className="page-hero"><span className="eyebrow">{page.label}</span><h1>{page.title}</h1><p>{page.intro}</p>{['product','features/files','features/documents','features/reports','features/local-ai'].includes(key)&&<a href={downloadHref} className="button">Download for macOS</a>}</section>{key==='product'&&<InterfacePreview/>}{(key.startsWith('features/')||key.startsWith('use-cases/'))&&<ProductDemo compact initial={key.includes('documents')||key.includes('students')?1:key.includes('files')?2:0}/>}<article className="prose">{page.sections.map(([h,p])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}</article></div>{!['terms','privacy'].includes(key)&&<CTA/>}</main>;
return <main id="main"><div className="wrap"><section className="page-hero"><span className="eyebrow">{key==='download'?'Errandly for macOS':key}</span><h1>{({download:'Good things have arrived.',pricing:'Useful AI. Without the overhead.',docs:'A good place to get started.',help:'A little help, right here.',blog:'Notes from the workbench.',changelog:'The journey to version one.',roadmap:'Small steps. Useful outcomes.',brand:'Meet the Errandly identity.'} as Record<string,string>)[key]}</h1><p>{({download:'Your personal AI for everyday work. Built for your Mac, with your files and your privacy in mind.',pricing:'A free core is part of the plan. Pay only for optional features you decide are worth it.',docs:'Explore the planned Errandly workflow. Installation instructions will arrive with the first release.',help:'Answers about availability, local AI, and the first release.',blog:'Ideas, decisions, and progress as we build a calmer way to work.',changelog:'Errandly is in development. This is where shipped releases and changes will be published.',roadmap:'We’re starting with a few everyday tasks and building a reliable foundation underneath them.',brand:'A simple identity for a little less everyday work.'}as Record<string,string>)[key]}</p></section><section className="page-body">
{key==='download'&&<><div className="download-box"><div className="download-mark"><div className="download-logo"><Logo/></div></div><div className="download-info"><span className="eyebrow">FIRST RELEASE / NOW AVAILABLE</span><h2>Errandly for Mac</h2><p>A local-first assistant for the work you do every day.</p><dl><div><dt>Architecture</dt><dd>Apple Silicon</dd></div><div><dt>Availability</dt><dd>Available now</dd></div><div><dt>Requirements</dt><dd>To be confirmed</dd></div></dl><a className="button" href={downloadHref}>Download for macOS<ArrowDown size={16}/></a><p style={{fontSize:12,marginTop:15}}>For Apple Silicon Macs. If macOS blocks the app on first open, see the help video below.</p></div></div><MacHelpVideo/><h2 className="section-title">A few things to know.</h2><FAQ/></>}
{key==='pricing'&&<><div className="content-grid"><div className="content-card"><span className="eyebrow">CORE</span><h3>Everyday essentials</h3><div className="price">Free <small>planned at launch</small></div><p>A useful foundation, on your own computer.</p><ul><li>Local AI conversations and task planning</li><li>File organization with approval</li><li>Supported PDF and spreadsheet workflows</li><li>Local task history and outputs</li><li>No mandatory AI API subscription</li></ul><Link href={B+"/download"} className="button">View availability</Link></div><div className="content-card"><span className="eyebrow">PRO / PLANNED</span><h3>A little more power</h3><div className="price">To come</div><p>Optional premium features are being explored.</p><ul><li>Feature scope is not finalized</li><li>Pricing will be announced before launch</li><li>No checkout or subscription is available yet</li></ul><Link href={B+"/roadmap"} className="accent-link">Explore the roadmap <ArrowUpRight size={14}/></Link></div><div className="content-card"><span className="eyebrow">YOUR CHOICE</span><h3>Bring your own AI</h3><div className="price">Optional</div><p>External model connections are planned for a later release.</p><ul><li>Use your own provider account</li><li>Authorize what leaves your Mac</li><li>Provider charges are separate</li><li>Local mode remains available</li></ul></div></div><FAQ/></>}
{key==='docs'&&<><div className="notice">Pre-release guide · These pages explain intended behavior. Final setup steps and tested system requirements are not available yet.</div><div className="content-grid">{[['01','Choose your workspace','Select the local files and folders Errandly can access.',B+'/features/files'],['02','Set up local AI','Download a compatible model and keep inference on your Mac.',B+'/features/local-ai'],['03','Describe your task','Ask for an outcome, review the plan, and inspect your results.',B+'/product']].map(([n,h,p,l])=><Link className="content-card" href={l} key={n}><span className="eyebrow">{n}</span><h3>{h}</h3><p>{p}</p></Link>)}</div><MacHelpVideo/><h2 className="section-title">Common questions</h2><FAQ/></>}
{key==='help'&&<><MacHelpVideo/><FAQ/></>}
{key==='blog'&&<div className="journal-list">{[['introducing-errandly','Introduction','A little less on your plate.','The idea behind an everyday AI assistant that lives on your Mac.'],['local-first','Product philosophy','Why your AI should feel at home.','A case for keeping intelligence close to the work.']].map(([s,l,h,p],i)=><Link className="journal-card" href={B+'/blog/'+s} key={s}><div className={'journal-art '+(i?'alt':'')}/><section><span className="eyebrow">{l}</span><h2>{h}</h2><p>{p}</p></section></Link>)}</div>}
{(key==='roadmap'||key==='changelog')&&<>{key==='changelog'&&<div className="notice">No public releases yet. The roadmap below shows development priorities, not shipped features or promised dates.</div>}{[['First release','The local foundation','An installable Apple Silicon app, local models, task planning, file organization, PDF processing, spreadsheet analysis, approvals, and supported undo.'],['Next','Deeper workflows','Reusable workflows, local semantic search, advanced OCR, Bengali-language support, and optional external AI connections.'],['Future exploration','Beyond the first Mac','Windows and Linux, voice commands, browser automation, and additional integrations. Scope and timing remain unconfirmed.']].map(([n,h,p])=><div className="roadmap-row" key={n}><span className="eyebrow">{n}</span><div><h2>{h}</h2><p>{p}</p></div></div>)}</>}
{key==='brand'&&<><div className="brand-preview"><Logo/></div><div className="prose"><h2>Errandly, by Foxmen Studio.</h2><p>The name is Errandly. Use the supplied symbol and wordmark together, as shown, and give them plenty of room.</p><h2>A mark for your Mac.</h2><p>The official horizontal logo is available as a transparent PNG for use when referring to Errandly.</p><a className="button" style={{marginTop:25}} href={B+"/errandly-logo.png"} download="errandly-logo.png">Download PNG logo</a></div></>}
</section></div>{!['download','pricing','brand'].includes(key)&&<CTA/>}</main>}
